In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [7]:
import numpy as np
rdm_mat = np.random.random((2,2))
rdm_mat = rdm_mat * 10
rdm_mat = np.array(rdm_mat, dtype='int')
print(rdm_mat)

[[8 8]
 [6 4]]


Donner le type de la variable rdm_mat

In [8]:
typ = rdm_mat.dtype
print(typ)

int32


Donner la somme des éléments de ce tableau 2D

In [10]:
somme = np.sum(rdm_mat)
print(rdm_mat)
somme

[[8 8]
 [6 4]]


26

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [11]:
print(rdm_mat)
max1 = rdm_mat[0].max()
max2 = rdm_mat[1].max()
print(max1);print(max2)

[[8 8]
 [6 4]]
8
8
4
6


Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [14]:
print(rdm_mat)
max1 = rdm_mat[:,0].max()
max2 = rdm_mat[:,1].max()
print(max1);print(max2)

[[8 8]
 [6 4]]
8
8


Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [21]:
rdm_vect = np.random.randn(100)
#rdm_vect.shape(np.array(rdm_mat),100)
rdm_vect

array([ 1.26361690e+00, -1.49203394e+00,  8.67675018e-01, -1.59341200e-01,
        5.32104566e-01,  3.23587546e-01,  3.04577999e-01, -1.29664769e+00,
        1.13342058e+00,  2.46976001e-01, -5.57261982e-01, -5.40136683e-01,
        2.48501097e+00,  5.29361413e-01,  1.25212002e+00,  6.24236602e-01,
        6.32070350e-01, -5.53560135e-01, -6.74207828e-01, -3.91036017e-01,
        7.12262218e-01,  8.99757751e-01, -1.46588963e+00, -9.95014114e-01,
       -9.70050465e-05,  9.73068494e-02, -1.19371105e+00, -6.39720254e-01,
       -1.14249208e+00,  9.72621485e-01,  5.34132966e-01, -7.82360847e-01,
       -8.83175186e-01, -9.65768368e-01,  3.28677696e-01, -9.11806655e-01,
       -1.30656607e+00, -7.01007445e-01,  1.19967087e+00, -3.39237832e-01,
       -4.09474865e-01, -5.00342817e-01, -1.07515085e+00,  6.44145675e-01,
       -1.82818033e+00, -6.49086927e-01,  9.69349135e-01, -1.72369604e+00,
       -5.21777585e-01,  5.96848107e-01,  2.81452728e-01, -5.81856779e-01,
       -8.73538451e-01,  

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [24]:
np.argmax(rdm_vect)


89

Afficher cette valeur 

In [27]:
rdm_vect.max()

2.498289843449232

Convertir le vecteur en un tableau 10, 10

In [29]:
rdm_vect.reshape(10,10)

array([[ 1.26361690e+00, -1.49203394e+00,  8.67675018e-01,
        -1.59341200e-01,  5.32104566e-01,  3.23587546e-01,
         3.04577999e-01, -1.29664769e+00,  1.13342058e+00,
         2.46976001e-01],
       [-5.57261982e-01, -5.40136683e-01,  2.48501097e+00,
         5.29361413e-01,  1.25212002e+00,  6.24236602e-01,
         6.32070350e-01, -5.53560135e-01, -6.74207828e-01,
        -3.91036017e-01],
       [ 7.12262218e-01,  8.99757751e-01, -1.46588963e+00,
        -9.95014114e-01, -9.70050465e-05,  9.73068494e-02,
        -1.19371105e+00, -6.39720254e-01, -1.14249208e+00,
         9.72621485e-01],
       [ 5.34132966e-01, -7.82360847e-01, -8.83175186e-01,
        -9.65768368e-01,  3.28677696e-01, -9.11806655e-01,
        -1.30656607e+00, -7.01007445e-01,  1.19967087e+00,
        -3.39237832e-01],
       [-4.09474865e-01, -5.00342817e-01, -1.07515085e+00,
         6.44145675e-01, -1.82818033e+00, -6.49086927e-01,
         9.69349135e-01, -1.72369604e+00, -5.21777585e-01,
         5.

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [41]:
moy = np.repeat(np.mean(rdm_vect),10)
moy

array([-0.09646938, -0.09646938, -0.09646938, -0.09646938, -0.09646938,
       -0.09646938, -0.09646938, -0.09646938, -0.09646938, -0.09646938])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

array([-9.64693759, -9.64693759, -9.64693759, -9.64693759, -9.64693759,
       -9.64693759, -9.64693759, -9.64693759, -9.64693759, -9.64693759])

Calculer la somme pour chaque ligne (sans boucles)

array([-2.45928276e+00,  3.30057119e+00, -6.94069374e-01,  1.16367130e-01,
       -7.35080583e-01,  1.78359994e-03, -1.12472416e+00,  9.99337195e+00,
       -1.69671892e+00,  1.56672647e+00])